config/routes.rb
Rails.application.routes.draw do
  post 'animal_pictures/get_fox'
  get 'animal_pictures/index'
  post 'animal_pictures/get_cat'
  post 'animal_pictures/get_dog'
  post 'animal_pictures/get_duck'
  resources :dummy_models
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dummy_model.rb
class DummyModel < ApplicationRecord
end

app/controllers/animal_pictures_controller.rb
class AnimalPicturesController < ApplicationController
  def get_fox
    client = Foxes::Client.new
    redirect_to action: :index, image_url: client.get_picture_url
  end
  def index
    @image_url = params[:image_url]
  end

  def get_cat
    client = Cats::Client.new
    redirect_to action: :index, image_url: client.get_picture_url
  end

  def get_dog
    client = Dogs::Client.new
    redirect_to action: :index, image_url: client.get_picture_url
  end

  def get_duck
    client = Ducks::Client.new
    redirect_to action: :index, image_url: client.get_picture_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dummy_models_controller.rb
class DummyModelsController < ApplicationController
  before_action :set_dummy_model, only: %i[ show edit update destroy ]

  # GET /dummy_models or /dummy_models.json
  def index
    @dummy_models = DummyModel.all
  end

  # GET /dummy_models/1 or /dummy_models/1.json
  def show
  end

  # GET /dummy_models/new
  def new
    @dummy_model = DummyModel.new
  end

  # GET /dummy_models/1/edit
  def edit
  end

  # POST /dummy_models or /dummy_models.json
  def create
    @dummy_model = DummyModel.new(dummy_model_params)

    respond_to do |format|
      if @dummy_model.save
        format.html { redirect_to @dummy_model, notice: "Dummy model was successfully created." }
        format.json { render :show, status: :created, location: @dummy_model }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dummy_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dummy_models/1 or /dummy_models/1.json
  def update
    respond_to do |format|
      if @dummy_model.update(dummy_model_params)
        format.html { redirect_to @dummy_model, notice: "Dummy model was successfully updated." }
        format.json { render :show, status: :ok, location: @dummy_model }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dummy_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dummy_models/1 or /dummy_models/1.json
  def destroy
    @dummy_model.destroy
    respond_to do |format|
      format.html { redirect_to dummy_models_url, notice: "Dummy model was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dummy_model
      @dummy_model = DummyModel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dummy_model_params
      params.require(:dummy_model).permit(:dummy_text1, :dummy_text2, :dummy_text3)
    end
end

app/helpers/animal_pictures_helper.rb
module AnimalPicturesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dummy_models_helper.rb
module DummyModelsHelper
end

app/views/animal_pictures/index.html.erb
<h1>AnimalPictures#index</h1>

<% unless @image_url.nil? %>
    <%= image_tag @image_url, size:"512x512" %>
<% end%>

<div id="actions">
    <%= button_to "Foxes", action: :get_fox %>

    <%= button_to "Cats", action: :get_cat %>
    <%= button_to "Dogs", action: :get_dog %>
    <%= button_to "Ducks", action: :get_duck %>
</div>

app/views/dummy_models/_form.html.erb
<%= form_with(model: dummy_model) do |form| %>
  <% if dummy_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dummy_model.errors.count, "error") %> prohibited this dummy_model from being saved:</h2>

      <ul>
        <% dummy_model.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dummy_text1 %>
    <%= form.text_field :dummy_text1 %>
  </div>

  <div class="field">
    <%= form.label :dummy_text2 %>
    <%= form.text_field :dummy_text2 %>
  </div>

  <div class="field">
    <%= form.label :dummy_text3 %>
    <%= form.text_field :dummy_text3 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dummy_models/edit.html.erb
<h1>Editing Dummy Model</h1>

<%= render 'form', dummy_model: @dummy_model %>

<%= link_to 'Show', @dummy_model %> |
<%= link_to 'Back', dummy_models_path %>

app/views/dummy_models/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dummy Models</h1>

<table>
  <thead>
    <tr>
      <th>Dummy text1</th>
      <th>Dummy text2</th>
      <th>Dummy text3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dummy_models.each do |dummy_model| %>
      <tr>
        <td><%= dummy_model.dummy_text1 %></td>
        <td><%= dummy_model.dummy_text2 %></td>
        <td><%= dummy_model.dummy_text3 %></td>
        <td><%= link_to 'Show', dummy_model %></td>
        <td><%= link_to 'Edit', edit_dummy_model_path(dummy_model) %></td>
        <td><%= link_to 'Destroy', dummy_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dummy Model', new_dummy_model_path %>

app/views/dummy_models/new.html.erb
<h1>New Dummy Model</h1>

<%= render 'form', dummy_model: @dummy_model %>

<%= link_to 'Back', dummy_models_path %>

app/views/dummy_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dummy text1:</strong>
  <%= @dummy_model.dummy_text1 %>
</p>

<p>
  <strong>Dummy text2:</strong>
  <%= @dummy_model.dummy_text2 %>
</p>

<p>
  <strong>Dummy text3:</strong>
  <%= @dummy_model.dummy_text3 %>
</p>

<%= link_to 'Edit', edit_dummy_model_path(@dummy_model) %> |
<%= link_to 'Back', dummy_models_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTestLab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>